### ISSUE TITLE
Can't find `call-process-region' in Emacs 26 source tree

### ISSUE THREAD

**Issue by rswgnu** [redguardtoo/counsel-etags#1]
Using your find at point etags command, the Emacs C-coded primitive (uses C DEFUN macro), call-process-region is not found when searched for from the cdl.el Lisp file.  Regular find-tag fine.  It takes over 4 seconds to not find this tag and then just give me a list of possible completion matches.

Also, after running this query, no TAGS file is written to the root project directory or anywhere else I can find.

I do like your concept, though.

Bob

**Comment by redguardtoo** [comment]
Currently I only support Emacs 24, 25 because 26 is not released yet.

**Comment by rswgnu** [comment]
Are you saying that the search would work properly in Emacs 24 or 25?  Have you tried it? Seems like the issue would be the same.

-- Bob

**Comment by redguardtoo** [comment]
Yes, it works on Emacs 24 and Emacs 25. You can use Emacs 25.3

**Comment by rswgnu** [comment]
I will try it running in Emacs 25 but I don't understand why there would or should be a behavioral difference when looking up the same tag in the same source.

-- Bob

**Comment by redguardtoo** [comment]
Emacs 26 is buggy because it's still in develop branch. Unless you are a Emacs developer, you'd better stick to stable version. Both 25.3 and 25.2 are fine. The only difference is 25.3 fixed a security issue.

**Comment by redguardtoo** [comment]
fixed now
