### ISSUE TITLE
Why not use executable-find to find programs on Windows?

### ISSUE THREAD

**Issue by kenhuang-io** [redguardtoo/counsel-etags#10]
Hi,

  Recently I try to use native Emacs with Cygwin on Windows because the Cygwin version occasionaly crashs.
It works almost fine, except that `counsel-etags-grep` complains that it can't find grep.

With some tracing, I find out it is due to my installing cygwin in `F:\`, which is not covered by [counsel-etags-guess-program](https://github.com/redguardtoo/counsel-etags/blob/master/counsel-etags.el#L258):

    (defun counsel-etags-guess-program (name)
      "Guess executable path from its NAME on Windows."
      (let* (rlt)
        (when (eq system-type 'windows-nt)
          (cond
           ((file-executable-p (setq rlt (concat "c:\\\\cygwin64\\\\bin\\\\" name ".exe"))))
           ((file-executable-p (setq rlt (concat "d:\\\\cygwin64\\\\bin\\\\" name ".exe"))))
           ((file-executable-p (setq rlt (concat "e:\\\\cygwin64\\\\bin\\\\" name ".exe"))))
           (t (setq rlt nil))))
        (if rlt rlt name)))
        
So my question is why not using `executable-find` to find the program? it works actually.(I've added `"f:/cygwin64/bin"` to `exec-path`).

**Comment by redguardtoo** [comment]
69e31f7 detect cli program on window (Chen Bin)

**Comment by kenhuang-io** [comment]
Thanks for your quick response, as always:)

But why not use `executable-find` to detect it directly? does it has any side effects?

**Comment by redguardtoo** [comment]
There is already one built in `find.exe` on Windows.

**Comment by kenhuang-io** [comment]
ok, thanks.

**Comment by kenhuang-io** [comment]
After updating, it still complain the below error when `M-x counsel-etags-grep`

    /usr/bin/bash: f:\\cygwin64\\bin\\grep.exe: command not found

It works fine after I changing the path style to:

    ((file-executable-p (setq rlt (concat "f:/cygwin64/bin/" name ".exe"))))

My emacs version is 25.3.1 on Windows 7.

**Comment by redguardtoo** [comment]
Can you test YOUR solution on Emacs 24.4?

**Comment by redguardtoo** [comment]
Native windows Emacs will start a **DOS shell** which only recognize the path like "f:\cygwin64\bin\grep.exe".

Cygwin Emacs run the commands in **BASH shell** which only recognized path like "/user/bin/grep".

Why your windows native Emacs start a bash shell?

I tested on Window, `counsel-etags` works out of the box.

**Comment by kenhuang-io** [comment]
According to [simple.el](https://github.com/emacs-mirror/emacs/blob/master/lisp/simple.el#L3842) of emacs, the `shell-file-name` is the shell to run, and unfortunately it's bash within my emacs, and there is no such setting in my .emacs.d, still don't know where it's set.

And if I run plain emacs with `runemacs -Q`, it's a path to `cmdproxy.exe` , which i think is the expected behavior.

UPDATE:
There are some packages in .emacs.d do touch `shell-file-name` actually, I will try to spot the culprit if I have more time.

**Comment by kenhuang-io** [comment]
Just find a workaround, SHELL env is set by emacs I believe:

    (when (eq system-type 'windows-nt)
      (setq shell-file-name (getenv "SHELL")))

**Comment by redguardtoo** [comment]
Output of `M-x emacs-version`? and what's `(getenv "SHELL")`?

**Comment by kenhuang-io** [comment]
version: `GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-27`

env: `"D:/tools/emacs-25.3_1-x86_64/libexec/emacs/25.3/x86_64-w64-mingw32/cmdproxy.exe"`, and runemacs.exe is located at `D:\tools\emacs-25.3_1-x86_64\bin\runemacs.exe`.

There is no `SHELL` in Windows' environment variables.

**Comment by kenhuang-io** [comment]
Oh, just found I've set it up within my .custom.el:

    (setq shell-file-name "bash")
    (setq explicit-shell-file-name shell-file-name)

sorry about that.

**Comment by redguardtoo** [comment]
I don't suggest changing Emacs's default shell. Use variable `default-diretory` and feed the cli program the relative path instead:
```lisp
(let* ((default-directory "C:\\\\What-ever-directory\\\\proj1"))
  (shell-command "ls -l .")
```

Then add `ivy`, see https://github.com/abo-abo/swiper/issues/591 , it's extremly powerful technique.

**Comment by kenhuang-io** [comment]
I copied these from somewhere regarding Windows settings, and I've forgot it:(

Thanks for your help and the tip.

**Comment by redguardtoo** [comment]
No worries. To be honest, I have read most Windows settings articles. Most of them are no better than my setup.

**Comment by kenhuang-io** [comment]
I copied these from [10 Tips for Powerful Emacs on Windows – Gregory Grubbs - gregorygrubbs.com](http://gregorygrubbs.com/emacs/10-tips-emacs-windows/) a few months ago, but I only managed to use native Windows emacs recently:( so I forgot about it totally.

Thank you for your emacs.d, it helped me get started with emacs and I learned a lot from it.
