### ISSUE TITLE
pop-tag-mark doesn't work

### ISSUE THREAD

**Issue by ashumilov** [redguardtoo/counsel-etags#12]
After calling 'counsel-etags-find-tag-at-point' and jumping to the function definition, 'pop-tag-mark' doesn't work with message "no previous locations for find-tag invocation".

Package-Version: 20180121.1738

**Comment by redguardtoo** [comment]
Output of `M-x emacs-version`?

**Comment by ashumilov** [comment]
GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org

**Comment by redguardtoo** [comment]
2219bf8 avoid using xref API on emacs24 (Chen Bin)
