### ISSUE TITLE
counsel-etags-open-file-api: Search failed

### ISSUE THREAD

**Issue by lemon0910** [redguardtoo/counsel-etags#14]
use counsel-etags-find-tags, I can find the result desplayed in buffer, but when I select one row and enter "Enter" key, I can't jump to the target file position, I get error:
Use M-x make-directory RET RET to create the directory and its parents
counsel-etags-open-file-api: Search failed: "hello"

**Comment by redguardtoo** [comment]
I need details. Could you setup a minimum sample?

Try `(setq counsel-etags-project-file '("TAGS" "tags" ".svn" ".hg" ".git" "TAGS" "tags"))`

**Comment by lemon0910** [comment]
In my preoject, I find some tags file. I delete them all and rebuild etags, It work now.
