### ISSUE TITLE
How to merge two TAGS file if I use counsel-etags-scan-code in different dirs?

### ISSUE THREAD

**Issue by BrianYi** [redguardtoo/counsel-etags#17]
At first, I use counsel-etags-scan-code at ~/.emacs.d/, of course it generate a TAGS file, but for some reason, there is some variables like **kill-emacs-query-functions** which is declared in file /usr/local/share/emacs/25.3/lisp/files.el.gz, I use counsel-etags-find-tag-at-point but cannot find the right position, so, I guess I should counset-etags-scan-code at /usr/local/share/emacs/25.3/lisp/ also, now, I don't know how to merge these two TAGS file into one, is there any tricky for this?

**Comment by redguardtoo** [comment]
No, you can't. We only support one tags file per project.

You can `M-x find-function` to jump to the Emacs Lisp function definition.

**Comment by BrianYi** [comment]
thks, got it. : )
