### ISSUE TITLE
counsel-etags-find-tag-at-point error when in *scratch* buffer

### ISSUE THREAD

**Issue by rswgnu** [redguardtoo/counsel-etags#2]
One idea to solve this would be to reuse any last TAGS file used from another location or to set a default file or file-list as regular find-tag does.

-----

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-as-directory(nil)
  counsel-etags-project-root()
  counsel-etags-tags-file-must-exist()
  counsel-etags-find-tag-at-point()
  funcall-interactively(counsel-etags-find-tag-at-point)
  call-interactively(counsel-etags-find-tag-at-point record nil)
  command-execute(counsel-etags-find-tag-at-point record)
  execute-extended-command(nil "counsel-etags-find-tag-at-point" "counsel-etags-find-tag-")
  funcall-interactively(execute-extended-command nil "counsel-etags-find-tag-at-point" "counsel-etags-find-tag-")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by redguardtoo** [comment]
Thanks. I fixed the issue.

You can also set `counsel-etags-project-root` in `.dir-local.el`
