### ISSUE TITLE
Make counsel-etags-scan-code message more compact in mini-buffer

### ISSUE THREAD

**Issue by Opioid** [redguardtoo/counsel-etags#20]
Periodically counsel-etags will update the tags file by running find and ctags. This creates a huge message that is displayed in the mini-buffer which suddenly grows many lines tall (at least on my setup).
I use (setq counsel-etags-quiet-when-updating-tags t) but it doesn't seem to make a difference. (Maybe those two things are not related).
Is it possible to make this message shorter, so that it comfortably fits in a single-line mini-buffer? As it is, it can be confusing to see the mini-buffer suddenly "jump" to a taller size. I wouldn't mind a short message telling me, that ctags is running, but especially the long list of arguments to find doesn't add value in my opinion.

**Comment by redguardtoo** [comment]
I'm working on a new branch `optimize` these day. The issue is fixed in that branch.

**Comment by Opioid** [comment]
Cool!
