### ISSUE TITLE
Recent ripgrep options format doesn't work with zsh

### ISSUE THREAD

**Issue by kenhuang-io** [redguardtoo/counsel-etags#22]
Hi,
  I'm afraid [this](https://github.com/redguardtoo/counsel-etags/commit/57b28e010440cd3619f941a7c958b40200a57493#diff-3e889175a525b2fb35c6b64d43fd3af8R876) breaks things with zsh on linux, `counsel-etags-grep` doesn't works now in my case.
Here is what it looks like in terminal:

    $ /usr/bin/rg -n -M 512 --no-heading --color never -s --path-separator / -g="!.git/* -g="!.svn/* -g="!.cvs/* -g="!.bzr/* -g="!.hg/* -g="!bin/* -g="!fonts/* -g="!images/* -g="!.DS_Store/* -g="!.npm/* -g="!.tmp/* -g="!.sass-cache/* -g="!.idea/* -g="!node_modules/* -g="!bower_components/* -g="!.tox/* -g="!.cask/* -g="!*.json -g="!*.log -g="!tags -g="!TAGS -g="!*.gz -g="!*.zip -g="!*.tar -g="!*.rar -g="!GTAGS -g="!GPATH -g="!GRTAGS -g="!cscope.files -g="!*bundle.js -g="!*min.js -g="!*min.css -g="!*.png -g="!*.jpg -g="!*.jpeg -g="!*.gif -g="!*.bmp -g="!*.tiff -g="!*.ico -g="!*.doc -g="!*.docx -g="!*.xls -g="!*.ppt -g="!*.pdf -g="!*.odt -g="!*.obj -g="!*.o -g="!*.a -g="!*.dylib -g="!*.lib -g="!*.d -g="!*.dll -g="!*.exe -g="!.metadata* -g="!*.class -g="!*.war -g="!*.jar -g="!*flymake -g="!#*# -g="!.#* -g="!*.swp -g="!*~ -g="!*.elc -g="!*.pyc "counsel-etags-grep" --
    zsh: event not found: .git/

But bash doesn't have this issue, and I can work around it by `let`ting `shell-file-name` to "/bin/bash".

**Comment by redguardtoo** [comment]
d78b24e fixed typo in counsel-etags-grep (Chen Bin)

**Comment by kenhuang-io** [comment]
nice, never thought it's just a typo:(
