### ISSUE TITLE
Wrong type argument: markerp, nil

### ISSUE THREAD

**Issue by karta0807913** [redguardtoo/counsel-etags#25]
Hi, I use emacs with your configure
when I use `counsel-etags-find-tag-at-point ` function
got error :Wrong type argument: markerp, nil

and the error detail is
```
ctags: invalid option -- 'e'
        Try 'ctags --help' for a complete list of options.
```

**Comment by redguardtoo** [comment]
You install wrong ctags. Check README.

If you are using macOS, delete the legacy ctags and install either exuberant ctags or universal ctags.

If you still prefer legacy ctags, customize `counsel-etags-update-tags-backend`.

**Comment by karta0807913** [comment]
thanks, I know what to do
