### ISSUE TITLE
error in process filter: Wrong type argument: markerp, nil

### ISSUE THREAD

**Issue by owensys** [redguardtoo/counsel-etags#32]
Win7 x64, Emacs-26.1-x86_64
> ctags --version
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jul  9 2009, 17:05:35
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +win32, +regex, +internal-sort
use M-x counsel-etags-scan-code and then select my vs project directory(.sln's dir), got a message:
Failed to create tags file.

> d:\cygwin64\bin>find.exe --version
find (GNU findutils) 4.6.0
Packaged by Cygwin (4.6.0-1)
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Eric B. Decker, James Youngman, and Kevin Dalley.
Features enabled: D_TYPE O_NOFOLLOW(enabled) LEAF_OPTIMISATION FTS(FTS_CWDFD) CB
O(level=2)

I add a message code in counsel-etags-async-shell-command:
(message (concat "command:" command))
```lisp
(defun counsel-etags-async-shell-command (command tags-file)
  "Execute string COMMAND and create TAGS-FILE asynchronously."
  (let* ((directory default-directory)
         ;; Run the shell command without any interrupt or extra information
         (buffer (generate-new-buffer "*Etags Generating Command*"))
         (display-buffer-alist '(("Etags Generating Command" display-buffer-no-window))))
    (with-current-buffer buffer
      (setq buffer-read-only nil)
      (let* ((inhibit-read-only t) proc)
        (erase-buffer))
      (display-buffer buffer '(nil (allow-no-window . t)))
      (setq default-directory directory)
      (setq proc (start-process "Shell" buffer shell-file-name
                                shell-command-switch command))
      (message (concat "command:" command)) ;;add this line
      (set-process-sentinel proc `(lambda (process signal)
                                    (let* ((status (process-status process)))
                                    (when (memq status '(exit signal))
                                      (cond
                                       ((string= (substring signal 0 -1) "finished")
                                        (let* ((cmd (car (cdr (cdr (process-command process))))))
                                          (if counsel-etags-debug (message "`%s` executed." cmd))
                                          ;; reload tags-file
                                          (when (and ,tags-file (file-exists-p ,tags-file))
                                            (message "Tags file %s was created." ,tags-file)
                                            (visit-tags-table ,tags-file t))))
                                       (t
                                        (message "Failed to create tags file.")))))))
      ;; Use the comint filter for proper handling of carriage motion
      ;; (see `comint-inhibit-carriage-motion'),.
      (set-process-filter proc 'comint-output-filter))))
```

try again counsel-etags-scan-code, got message:
> d:\\cygwin64\\bin\\find.exe . \( -iwholename "*/.git/*" -or -iwholename "*/.svn/*" -or -iwholename "*/.cvs/*" -or -iwholename "*/.bzr/*" -or -iwholename "*/.hg/*" -or -iwholename "*/bin/*" -or -iwholename "*/fonts/*" -or -iwholename "*/images/*" -or -iwholename "*/.DS_Store/*" -or -iwholename "*/.npm/*" -or -iwholename "*/.tmp/*" -or -iwholename "*/.sass-cache/*" -or -iwholename "*/.idea/*" -or -iwholename "*/node_modules/*" -or -iwholename "*/bower_components/*" -or -iwholename "*/.tox/*" -or -iwholename "*/.cask/*" \) -prune -o -type f -not -size +512k -not -name "*.exp" -not -name "*.sln" -not -name "*.make" -not -name "*.htm" -not -name "*.vcxproj" -not -name "*.vcproj" -not -name "*.user" -not -name "*.filters" -not -name "*.pdb" -not -name "*.md" -not -name "*.tlog" -not -name "*.qrc" -not -name "*.rc" -not -name "moc_*.cpp" -not -name "*.ui" -not -name "ui_*.h" -not -name "*.json" -not -name "*.log" -not -name "tags" -not -name "TAGS" -not -name "*.tgz" -not -name "*.gz" -not -name "*.xz" -not -name "*.zip" -not -name "*.tar" -not -name "*.rar" -not -name "GTAGS" -not -name "GPATH" -not -name "GRTAGS" -not -name "cscope.files" -not -name "*bundle.js" -not -name "*min.js" -not -name "*min.css" -not -name "*.png" -not -name "*.jpg" -not -name "*.jpeg" -not -name "*.gif" -not -name "*.bmp" -not -name "*.tiff" -not -name "*.ico" -not -name "*.doc" -not -name "*.docx" -not -name "*.xls" -not -name "*.ppt" -not -name "*.pdf" -not -name "*.odt" -not -name "*.obj" -not -name "*.so" -not -name "*.o" -not -name "*.a" -not -name "*.ifso" -not -name "*.tbd" -not -name "*.dylib" -not -name "*.lib" -not -name "*.d" -not -name "*.dll" -not -name "*.exe" -not -name ".metadata*" -not -name "*.class" -not -name "*.war" -not -name "*.jar" -not -name "*flymake" -not -name "#*#" -not -name ".#*" -not -name "*.swp" -not -name "*~" -not -name "*.elc" -not -name "*.pyc" -print | ctags -e -L -
error in process filter: recursive-edit: Wrong type argument: markerp, nil

then i copy this to dos, got message:
> ctags.exe: out of memory
/usr/bin/find: 'standard output'
/usr/bin/find: write error

If remove -e arg in dos command, generate a tags file success. dir:
2019/01/19  15:30         3,781,719 tags

If i use toggle-debug-on-error, got *Backtrace*:

> Debugger entered--Lisp error: (wrong-type-argument markerp nil)
  comint-output-filter(#<process Shell> "ctags: out of memory\n/usr/bin/find: 'standard output'\n/usr/bin/find: write error\n")

**Comment by owensys** [comment]
I just download [Universal Ctags](https://github.com/universal-ctags/ctags-win32/releases) and replace Exuberant Ctags.
then counsel-etags-scan-code will generate a TAGS success!
the counsel-etags-find-tag and counsel-etags-find-tag-at-point works fine.

The Exuberant Ctags is download from [http://prdownloads.sourceforge.net/ctags/ctags58.zip](http://prdownloads.sourceforge.net/ctags/ctags58.zip)
and the emacs is download from [http://mirrors.ustc.edu.cn/gnu/emacs/windows/emacs-26/](http://mirrors.ustc.edu.cn/gnu/emacs/windows/emacs-26/), not installed from msys2 or cygwin.
is something wrong?
can not use Exuberant Ctags with this emacs version(not cygwin and msys)?

**Comment by redguardtoo** [comment]
Emacs doesn't matter. ctags is the trouble makers. The exuberant ctags you downloaded might not work for latest windows API. Cygwin ctags or universal-ctags should work.

**Comment by owensys** [comment]
Thanks.
