### ISSUE TITLE
Lots of *Etags Generating Command* buffers

### ISSUE THREAD

**Issue by jnuevo** [redguardtoo/counsel-etags#37]
Thanks for this great package.

After leaving Emacs open for a few hours, I usually end up with dozens of buffers called *Emacs Generating Command*. My elisp is very poor, but from reading the code I understand that these are created when the TAGS command is (re-)created.

Having that many buffers is not a big issue, but it's annoying. This happens on both Ubuntu and macOS, with Emacs 25.1 and 27. (My emacs setup is the same in both machines).

**Comment by redguardtoo** [comment]
01394c6 do NOT create extra buffer when running shell async command (Chen Bin)

**Comment by jnuevo** [comment]
Great, thanks!
