### ISSUE TITLE
Problem with case insensitive counsel-etags-find-tag

### ISSUE THREAD

**Issue by ribtoks** [redguardtoo/counsel-etags#39]
Hi

Thanks for so cool project. Almost everything works like a charm!

I have a small problem with `counsel-etags-find-tag` on Windows 10 with Emacs 26.1 (also I have `ripgrep` in my `PATH` and all other apps like `find` as well). 

The problem is that I cannot find results by doing case-insensitive search. If there's tag `ThisIsATag` and I run `counsel-etags-find-tag` and search `thisisa`, the tag is not found. I tried setting grep program as `rg -i` or `(setq counsel-etags-case-sensitive nil)` etc. to explicitly ignore case, but nothing helps. Searching `counsel-etags-find-tag-at-point` finds all the results.

I hope that this is just my misuse but may be some issue as well.

Thanks,
Taras

**Comment by redguardtoo** [comment]
find tags algorithm is written in emacs lisp.

It has nothing to do with grep program. I need read my code to understand why `counsel-etags-find-tag` is case sensitive.

**Comment by redguardtoo** [comment]
good idea. Now `counsel-etags-list-tag` and `counsel-etags-find-tag` are case insensitive.

1ac025e ignore case when fuzzy search tag (Chen Bin)

**Comment by ribtoks** [comment]
Cool, thank you so much! Do you have any idea when it will be available as melpa package?

**Comment by redguardtoo** [comment]
Already available.
https://melpa.org/#/counsel-etags

**Comment by ribtoks** [comment]
I hope it will make it to melpa-stable as well. Thanks for fast responses!

**Comment by redguardtoo** [comment]
v1.8.2 is released
