### ISSUE TITLE
使用counsel-etags-find-tag报错

### ISSUE THREAD

**Issue by zbjxb** [redguardtoo/counsel-etags#4]
我不是太清楚是否还需要配置什么，我下载counsel-etags.el文件到load-path指定的目录后，执行下面两句，结果成功，没问题。
(add-to-list 'load-path "~/.emacs.d/lisp/")
(require 'counsel-etags)
然后，配置了下面两个变量：
![counsel-var](https://user-images.githubusercontent.com/4047306/32699385-c3018524-c7ef-11e7-9ef7-81780bb59b11.png)

执行时，就报下面的错了：
![counsel-etags](https://user-images.githubusercontent.com/4047306/32699397-ea573e34-c7ef-11e7-8140-1d9da92e3c4d.png)

求帮助。

**Comment by zbjxb** [comment]
我看这个Readme.org上写的，似乎是执行add-to-list和require之后，就能正常使用了，所以不是太确定是不是有些常识我没有get到。

**Comment by redguardtoo** [comment]
Have you installed ctags?

**Comment by redguardtoo** [comment]
be0a14a counsel-etags-find-tag will find tags file at first too (Chen Bin)
