### ISSUE TITLE
Use different tags generator dependent on project language

### ISSUE THREAD

**Issue by Opioid** [redguardtoo/counsel-etags#40]
For example I want to use [rusty-tags](https://docs.rs/crate/rusty-tags/) for if I am in a rust project.

Manually calling `rusty-tags emacs` will generate a usable tags file, which then can be used with counsel-etags, but I would like to automatically always use this backend, including auto-update and so on. Is this possible? Is counsel-etags the right level to handle this?

**Comment by redguardtoo** [comment]
See `counsel-etags-update-tags-backend` in latest code.

```
(setq counsel-etags-update-tags-backend
      (lambda (src-dir)
        (cond
         ((string-match "myproj1" src-dir)
          (shell-command "rust-tags ~/projs/myproj1"))
         (t
          (counsel-etags-scan-dir-internal src-dir)))))
```

**Comment by Opioid** [comment]
When I try the code you provided I get a message about "Wrong number of arguments: (lambda (src-dir) [...]), 0". Any idea what that could mean?
(EDIT: I'm not sure if I updated after your last changes. I will try again tomorrow on that machine.)

Is there a way to try to guess the project languange? E.g. look for Cargo.toml to detect rust or maybe a .counseletags file to make per project configurations?

**Comment by Opioid** [comment]
It works! Thanks!

I am still interested in a way to handle this in a more generic way, or at least control the settings per project. Do you have any ideas?

**Comment by redguardtoo** [comment]
Could you give me an example? What's the project directory layout?

**Comment by Opioid** [comment]
The easiest way I can think of, would be to have something like a `.counesl-etags` file in the root folder, containing `counsel-etags-update-tags-backend = rusty-etags` or whatever. Then you could configure on a per project basis from within the project.

Another possibility would maybe be to somehow couple it to the current major-mode. So in my example, if we are in rust-mode then always use the following backend. For another-mode use this-and-that and for all other cases use the default.

I also noticed, that generating the TAGS file the first time indeed works with the specified backend, but subsequent updates don't work for some reason.

*Messages*-buffer contains this for initial creation:

> counsel-etags-scan-dir called => e:/projects/workspace/projects/bud/
> Fetching source and metadata ...
> Creating tags for: ["bud"] ...

*Messages*-buffer contains this for updates:

> Making tags completion table for e:/projects/workspace/projects/bud/TAGS...done

So maybe it is not calling the same backend?

**Comment by redguardtoo** [comment]
Use `.dir-locals.el`, see https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html

 `counsel-etags-update-tags-backend` is used to create tags file. The backend runs every 3 minutes and it's a quiet process.

The last message is output of API `tags-completion-table` which is NOT used by `counsel-etags`.

I don't know which 3rd party plugins is using it. Maybe `company-etags` from `company-mode`?

**Comment by Opioid** [comment]
Ok, I can use `.dir-locals.el`!

Hm. For some reason I thought the TAGS are updated on save as well. If it is always updated after `counsel-etags-update-interval`, I just wasn't patient enough.
