### ISSUE TITLE
Failed to create tags file (New issue on linux)

### ISSUE THREAD

**Issue by Opioid** [redguardtoo/counsel-etags#41]
On a linux machine where I used counsel-etags before, I suddenly get the following error when starting a tags search for the first time, before the TAGS file has been created.

> counsel-etags-scan-dir called => /home/beni/workspace/projects/sprout/
> counsel-etags-get-scan-command called => find-program=/usr/bin/find ctags-program=/usr/bin/ctags cmd=/usr/bin/find . \( -iwholename "*/.vscode" -or -iwholename "*/tools" -or -iwholename "*/test" -or -iwholename "*/extern" -or -iwholename "*/doc" -or -iwholename "*/deps" -or -iwholename "*/data" -or -iwholename "*/build" -or -iwholename "*/.git" -or -iwholename "*/.svn" -or -iwholename "*/.cvs" -or -iwholename "*/.bzr" -or -iwholename "*/.hg" -or -iwholename "*/bin" -or -iwholename "*/fonts" -or -iwholename "*/images" -or -iwholename "*/.DS_Store" -or -iwholename "*/.npm" -or -iwholename "*/.tmp" -or -iwholename "*/.sass-cache" -or -iwholename "*/.idea" -or -iwholename "*/node_modules" -or -iwholename "*/bower_components" -or -iwholename "*/.tox" -or -iwholename "*/.cask" \) -prune -o -type f -not -size +800k -not -name ".clang-format" -not -name "*.log" -not -name "tags" -not -name "TAGS" -not -name "*.tgz" -not -name "*.gz" -not -name "*.xz" -not -name "*.zip" -not -name "*.tar" -not -name "*.rar" -not -name "GTAGS" -not -name "GPATH" -not -name "GRTAGS" -not -name "cscope.files" -not -name "*bundle.js" -not -name "*min.js" -not -name "*min.css" -not -name "*.png" -not -name "*.jpg" -not -name "*.jpeg" -not -name "*.gif" -not -name "*.bmp" -not -name "*.tiff" -not -name "*.ico" -not -name "*.doc" -not -name "*.docx" -not -name "*.xls" -not -name "*.ppt" -not -name "*.pdf" -not -name "*.odt" -not -name "*.obj" -not -name "*.so" -not -name "*.o" -not -name "*.a" -not -name "*.ifso" -not -name "*.tbd" -not -name "*.dylib" -not -name "*.lib" -not -name "*.d" -not -name "*.dll" -not -name "*.exe" -not -name ".metadata*" -not -name "*.class" -not -name "*.war" -not -name "*.jar" -not -name "*flymake" -not -name "#*#" -not -name ".#*" -not -name "*.swp" -not -name "*~" -not -name "*.elc" -not -name "*.pyc" -print | /usr/bin/ctags -e --options="/home/beni/.ctags" -L -
> counsel-etags-scan-dir-internal called => src-dir=/home/beni/workspace/projects/sprout/ find-program=/usr/bin/find ctags-program=/usr/bin/ctags default-directory=/home/beni/workspace/projects/sprout/ cmd=/usr/bin/find . \( -iwholename "*/.vscode" -or -iwholename "*/tools" -or -iwholename "*/test" -or -iwholename "*/extern" -or -iwholename "*/doc" -or -iwholename "*/deps" -or -iwholename "*/data" -or -iwholename "*/build" -or -iwholename "*/.git" -or -iwholename "*/.svn" -or -iwholename "*/.cvs" -or -iwholename "*/.bzr" -or -iwholename "*/.hg" -or -iwholename "*/bin" -or -iwholename "*/fonts" -or -iwholename "*/images" -or -iwholename "*/.DS_Store" -or -iwholename "*/.npm" -or -iwholename "*/.tmp" -or -iwholename "*/.sass-cache" -or -iwholename "*/.idea" -or -iwholename "*/node_modules" -or -iwholename "*/bower_components" -or -iwholename "*/.tox" -or -iwholename "*/.cask" \) -prune -o -type f -not -size +800k -not -name ".clang-format" -not -name "*.log" -not -name "tags" -not -name "TAGS" -not -name "*.tgz" -not -name "*.gz" -not -name "*.xz" -not -name "*.zip" -not -name "*.tar" -not -name "*.rar" -not -name "GTAGS" -not -name "GPATH" -not -name "GRTAGS" -not -name "cscope.files" -not -name "*bundle.js" -not -name "*min.js" -not -name "*min.css" -not -name "*.png" -not -name "*.jpg" -not -name "*.jpeg" -not -name "*.gif" -not -name "*.bmp" -not -name "*.tiff" -not -name "*.ico" -not -name "*.doc" -not -name "*.docx" -not -name "*.xls" -not -name "*.ppt" -not -name "*.pdf" -not -name "*.odt" -not -name "*.obj" -not -name "*.so" -not -name "*.o" -not -name "*.a" -not -name "*.ifso" -not -name "*.tbd" -not -name "*.dylib" -not -name "*.lib" -not -name "*.d" -not -name "*.dll" -not -name "*.exe" -not -name ".metadata*" -not -name "*.class" -not -name "*.war" -not -name "*.jar" -not -name "*flymake" -not -name "#*#" -not -name ".#*" -not -name "*.swp" -not -name "*~" -not -name "*.elc" -not -name "*.pyc" -print | /usr/bin/ctags -e --options="/home/beni/.ctags" -L -
> /usr/bin/find . \( -iwholename "*/.vscode" -or -iwholename "*/tools" -or -iwholename "*/test" -or -iwholename "*/extern" -or -iwholename "*/doc" -or -iwholename "*/deps" -or -iwholename "*/data" -or -iwholename "*/build" -or -iwholename "*/.git" -or -iwholename "*/.svn" -or -iwholename "*/.cvs" -or -iwholename "*/.bzr" -or -iwholename "*/.hg" -or -iwholename "*/bin" -or -iwholename "*/fonts" -or -iwholename "*/images" -or -iwholename "*/.DS_Store" -or -iwholename "*/.npm" -or -iwholename "*/.tmp" -or -iwholename "*/.sass-cache" -or -iwholename "*/.idea" -or -iwholename "*/node_modules" -or -iwholename "*/bower_components" -or -iwholename "*/.tox" -or -iwholename "*/.cask" \) -prune -o -type f -not -size +800k -not -name ".clang-format" -not -name "*.log" -not -name "tags" -not -name "TAGS" -not -name "*.tgz" -not -name "*.gz" -not -name "*.xz" -not -name "*.zip" -not -name "*.tar" -not -name "*.rar" -not -name "GTAGS" -not -name "GPATH" -not -name "GRTAGS" -not -name "cscope.files" -not -name "*bundle.js" -not -name "*min.js" -not -name "*min.css" -not -name "*.png" -not -name "*.jpg" -not -name "*.jpeg" -not -name "*.gif" -not -name "*.bmp" -not -name "*.tiff" -not -name "*.ico" -not -name "*.doc" -not -name "*.docx" -not -name "*.xls" -not -name "*.ppt" -not -name "*.pdf" -not -name "*.odt" -not -name "*.obj" -not -name "*.so" -not -name "*.o" -not -name "*.a" -not -name "*.ifso" -not -name "*.tbd" -not -name "*.dylib" -not -name "*.lib" -not -name "*.d" -not -name "*.dll" -not -name "*.exe" -not -name ".metadata*" -not -name "*.class" -not -name "*.war" -not -name "*.jar" -not -name "*flymake" -not -name "#*#" -not -name ".#*" -not -name "*.swp" -not -name "*~" -not -name "*.elc" -not -name "*.pyc" -print | /usr/bin/ctags -e --options="/home/beni/.ctags" -L - at /home/beni/workspace/projects/sprout/
> counsel-etags-find-tag-api called => info nil nil
> Failed to create tags file.

**Comment by redguardtoo** [comment]
I tried latest `counsel-etags`, looks OK to me.
Running the full cli in shell does create tags file, right?
When running `counsel-etags-find-tag` for the first time, it's supposed to return nothing because tags files is not created.

**Comment by Opioid** [comment]
Sorry, apparently I messed something up with my ctags program. All is in order after further investigation.
