### ISSUE TITLE
Does counsel-etags support include in tags file?

### ISSUE THREAD

**Issue by Opioid** [redguardtoo/counsel-etags#42]
I have recently encountered TAGS files that contain lines like the following at the bottom of the file: `C:\Users\me\.rusty-tags\cache\base-634785015357407805.emacs,include`. As far as I can tell, counsel-etags does not include those tags in its search. Should this be supported?

**Comment by redguardtoo** [comment]
What's that? I can support it if you could design a minimum sample project.

**Comment by Opioid** [comment]
I stumbled upon it while using rusty-tags, which produce such files under certain circumstances:
[https://github.com/dan-t/rusty-tags/issues/41](https://github.com/dan-t/rusty-tags/issues/41)

What do you need? Is it enough to have a couple of source files and their corresponding TAGS files? Or do you to regenerate the tags sometimes?

**Comment by redguardtoo** [comment]
I need a sample project and steps to create tags containing `include`

**Comment by Opioid** [comment]
I see. The problem is, that currently the only way I know of, to create tags containing include, involves installation of rust and rusty-tags. I suspect we are looking for a more minimal approach?

**Comment by redguardtoo** [comment]
I've already installed rust and rust-tags. Is there any open source rust project which I can reproduce the issue?

**Comment by Opioid** [comment]
This is my project: https://github.com/Opioid/bud It is still small (but has a dependency to serde_json) and multiple tag files are created for it. If you want I can create a minimal project though.

**Comment by redguardtoo** [comment]
79a0574 support rusty-tags (Chen Bin)

**Comment by Opioid** [comment]
Cool, thanks!
