### ISSUE TITLE
Customize tags program and can not work.

### ISSUE THREAD

**Issue by maobaoqi** [redguardtoo/counsel-etags#44]
Hi, Mr. Chen, I try this package today on Emacs and it's great! But when I want to customize tag program ,for example, set `counsel-etags-tags-program` variable to "etags" and it can not create tag file using `counsel-etags-scan-code` after that. 
![Snipaste_2019-05-14_16-42-12](https://user-images.githubusercontent.com/3353791/57683961-574ec580-7667-11e9-9704-ee6d6782ee1c.png)

Another question, I use it on MSYS2, not set tag program, it can not find installed ctags program, show `Please install Ctags before run this program!`. I can not find where is going wrong.

Last question, if I create TAGS file in a specify folder not under current project folder using CLI, How to use this TAGS according counsel-etags. I try to use Emacs `visit-tags-table` but also call `ctags scan code` under current project folder. 

Thanks!

**Comment by redguardtoo** [comment]
What Emacs you are using? OS? What's output of etags in cli? What's output of ctags in cli?

**Comment by maobaoqi** [comment]
Thanks for reply!   @redguardtoo 

I use Win10 and ArchLinux. 

For the first and second question, I solved by this setting on Win10 MSYS2. Not use `pacman -S ctags` on MSYS2, and copy another ctags.exe on Windows into MSYS2 bin folder.
![Snipaste_2019-05-15_08-48-01](https://user-images.githubusercontent.com/3353791/57741311-de934c00-76ee-11e9-9acc-4b032f6bd444.png)

For the last question, Should the project root folder contains TAGS file? In some cases, I do not want to produce TAGS file under project source tree and want to keep the project folder clean.

Additional, if develop a new project using tags jump and complete, this project will use two extra libraries, for example, opencv and glib,
What is the best workflow to generate TAGS when programming C++ ? under one specify tag folder? I have no idea by spending one night to learn.

On archlinux, when open a github clone source code folder, it should be checked as project folder automatically, but it's not do that and always open home folder when call `counsel-etags-scan-code` command. However, for same github clone source code folder on Win10, it can identify this folder as project folder. (I use github `ccv` project for testing). I think it's better to open current folder after run `counsel-etags-scan-code`.

Thanks! Mr.Chen

**Comment by redguardtoo** [comment]
You have to create tags file in your own project root. Or else things could be unnecessary complicated. For example, if tags file is not in project root, you have to use absolute path for each tag, so tags file is not portable any more.

For 3rd party tags files, see https://github.com/redguardtoo/counsel-etags#specify-multiple-tags-files

Please note `counsel-etags` only read from 3rd party tags files. It won't create/update them. So you need manually create these tags files. It doesn't matter where they are placed.

**Comment by maobaoqi** [comment]
@redguardtoo OK, I have to create TAGS file under my project folder and I get into another trouble.;)

Create tags for 3rd party in a single folder and set its path for `counsel-etags-extra-tags-files`, then I also create tag file in project root folder. When open .cpp file, it can jump but can not complete 3rd party functions using company-etags. From minibuffer information, I find that company-etags just use the project root folder tag file. What's going wrong?

I'm sorry for asking many times and I'm getting more and more confused. Thanks!
![Snipaste_2019-05-15_13-19-41](https://user-images.githubusercontent.com/3353791/57750308-4dcf6700-7714-11e9-9d1e-05f1493d7eca.png)
![Snipaste_2019-05-15_13-30-59](https://user-images.githubusercontent.com/3353791/57750700-d26eb500-7715-11e9-8528-dfd493cd95a9.png)

**Comment by redguardtoo** [comment]
Check README, the tag in 3rd party tags file should use full path, not relative path.

besides, ctags use `-e` to create tags file for Emacs.

I created a step by step guide in README.

**Comment by russellfei** [comment]
@redguardtoo 
The instructions in readme about ctags program customization
```emacs-lisp
(setq counsel-etags-update-tags-backend (lambda () (shell-command "find . -type f -iname \"*.[ch]\" | etags -")))
```
should be changed to 

```emacs-lisp
(setq counsel-etags-update-tags-backend (lambda (x) (shell-command "find . -type f -iname \"*.[ch]\" | etags -")))
```

otherwise, you will got errors like **Wrong number of input `(lambda nil ...), 1`** 

A few minutes to get this correct.

**Comment by redguardtoo** [comment]
d7fcec5 typo in README (Chen Bin)
