### ISSUE TITLE
Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by maca** [redguardtoo/counsel-etags#46]
Hi I am getting started with emacs and counsel/ivy/counse-etags

But `counse-etags-list-tag` is not working for me.

I get the message above and no results are presented.

**Comment by redguardtoo** [comment]
`M-x toggle-debug-on-error`, reproduce the issue and give the full error message.

**Comment by maca** [comment]
Hi @redguardtoo 

There wasn't more info in the \*Messages\* buffer or the autocomplete buffer.


```
Loading server...done
Turning on magit-auto-revert-mode...done
For information about GNU Emacs and the GNU system, type C-h C-a.
Starting a new list of tags tables
Followed link to /home/maca/dotfiles/emacs.el
Loading /home/maca/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
Debug on Error enabled globally
You can run the command ‘toggle-debug-on-error’ with M-x t-er RET
Debug on Error enabled globally
```

M-x counsel-etag-list-tag <enter>
Start typing, when reaches 3 charters:

```
Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument stringp nil)
```

counsel is counsel-20190718.1805
ivy is ivy-20190717.1355

and counsel-etags
counsel-etags-20190710.807


Here's the counsel-etags conf in my .emacs:

https://github.com/maca/dotfiles/blob/472bcee0b3244ba4d15dec82799e64a2184913dd/emacs.el#L134-L151


`counsel-etags-find-tag-at-point` works fine and it will fallback to grep search if the tag is not present

**Comment by maca** [comment]
This is my .emacs file:

https://github.com/maca/dotfiles/blob/472bcee0b3244ba4d15dec82799e64a2184913dd/emacs.el
Just in case

**Comment by redguardtoo** [comment]
Looks it's ivy problem. Try ivy-20190719.1839 

Besides, check #45 , see my last comment on how to set up `counsel-etags` with `use-package`

**Comment by maca** [comment]
Thanks, 

I've tried with ivy-20190719.1839 but I still get the same error


```
$ ls .emacs.d/elpa/ | grep -E 'ivy|counsel'                              
counsel-20190718.1805
counsel-etags-20190720.350
ivy-20190719.1839
```


Also, is this the correct setup for `counsel-etags` using `use-package`?

https://github.com/maca/dotfiles/blob/d27567c325aea7c8268562ae20b7ece9b8e7ef24/emacs.el#L160-L186


Thank you

**Comment by redguardtoo** [comment]
What's your Emacs version?
Besides, just double check, after `M-x toggle-debug-on-error`, you got no more detailed error message?

**Comment by maca** [comment]
Hi, I didn't get any additional messages.
emacs version is 27.0.50

**Comment by redguardtoo** [comment]
OK, as I suspected. Could be latest emacs problem.

**Comment by redguardtoo** [comment]
d037c8bb upgrade counsel-etags (Chen Bin)

**Comment by redguardtoo** [comment]
a6402fe compatible with Emacs 27 (Chen Bin)

**Comment by maca** [comment]
It's working now! :)

Thank you!
