### ISSUE TITLE
Feature request: list all tags in the current buffer (`counsel-etags-list-tag-current-buffer`)

### ISSUE THREAD

**Issue by xuhdev** [redguardtoo/counsel-etags#47]
It would be nice to have a command that lists all symbols in the current buffer, for a nice overview of what's going on in the current buffer.

**Comment by redguardtoo** [comment]
imenu?

**Comment by redguardtoo** [comment]
On second thought, I think you proposal make sense. Give me some time to investigate.

**Comment by xuhdev** [comment]
Thanks! I am thinking about something like a swiper behavior, but instead of searching the whole buffer, it only searches for tags.

**Comment by redguardtoo** [comment]
0e67373 can list tags in one file (Chen Bin)

**Comment by xuhdev** [comment]
Thanks!

**Comment by redguardtoo** [comment]
I updated the code, now it's full compatible with imenu.
