### ISSUE TITLE
Emacs 27: Error: `add-to-list' can't use lexical var `rlt'; 

### ISSUE THREAD

**Issue by ShuguangSun** [redguardtoo/counsel-etags#49]
```
In counsel-etags-add-tags-file-to-history:
counsel-etags.el:520:26:Error: `add-to-list' can't use lexical var `rlt'; use
    `push' or `cl-pushnew'
counsel-etags.el:582:1:Warning: Lexical argument shadows the dynamic variable
    find-program
counsel-etags.el:713:1:Warning: Unused lexical variable `rlt'
```

In GNU Emacs 27.0.50 (build 2, x86_64-w64-mingw32)
 of 2019-10-31 built on ...
Repository revision: e65be8cc5b623385ebe31aa0a1089e0de2b075b5
Repository branch: master
Windowing system distributor 'Microsoft Corp.', version 10.0.18362
System Description: Microsoft Windows 10 Enterprise (v10.0.1903.18362.418)

**Comment by jnuevo** [comment]
I'm also seeing that same issue, when using emacs 26.3 installed with macports on MacOS 10.14

**Comment by redguardtoo** [comment]
137b892 bye add-to-list (Chen Bin)
