### ISSUE TITLE
Emacs26 backward/forward-word will not stop at special character such as underline

### ISSUE THREAD

**Issue by Yangruipis** [redguardtoo/counsel-etags#51]
比如一个命名： `aaa_bbb_ccc| `，`|`表示光标位置，本来 backward-word (M-b) 后光标位置为：`aaa_bbb_|ccc`，在调用了 counsel-etags-find-tag-at-point 后，光标位置直接跳过了中间的"_"，变成`|aaa_bbb_ccc`

**Comment by redguardtoo** [comment]
What's the `major-mode`?

**Comment by Yangruipis** [comment]
> What's the `major-mode`?

Thanks for your reply, I got this issue in python-mode and sh-mode. In c++-mode It works fine.

**Comment by redguardtoo** [comment]
9fae8ad restore syntax table after extracting tag names (Chen Bin)

**Comment by Yangruipis** [comment]
Thanks！It works for me~~~
