### ISSUE TITLE
Shortcut navigation in Rust not finding standard library tags

### ISSUE THREAD

**Issue by ivnsch** [redguardtoo/counsel-etags#52]
I followed setup instructions from https://github.com/dan-t/rusty-tags

Installed universal ctags, rusty-tags, called `rusty-tags emacs` in the project's root, followed the "standard library support" section, i.e. set `RUST_SRC_PATH` in my `~/.profile` (`echo $RUST_SRC_PATH`) outputs this: `/Users/me/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/`, installed `counsel-etags`, created `.dir-locals.el` in my project's root with these contents:

```
((nil . ((counsel-etags-update-tags-backend . (lambda (src-dir) (shell-command "rusty-tags emacs")))
         (counsel-etags-extra-tags-files . ("~/third-party-lib/rusty-tags.emacs" "$RUST_SRC_PATH/rusty-tags.emacs"))
         (counsel-etags-tags-file-name . "rusty-tags.emacs"))))
```

After all this, I start emacs, press shortcut (using evil mode - `CTRL+]`) on `Result` (which is a type of Rust's standard lib). 
Prompt appears: `Visit tags table (default TAGS): ~/myProjectRoot/src/`
I edit the path to this: `~/myProjectRoot/rusty-tags.emacs`
Now it works for local tags, but not the standard lib, since it's not in this file. So it can't find anything for `Result`.

How do I configure it to recognize both? I thought that `.dir-locals.el` perhaps does this, but it seems to have no effect as I'm prompted to enter a path.

Note that if I don't use shortcut navigation, but `M-x counsel-etags-find-tag-at-point` it works for both local and standard lib tags.

I asked in rusty-tags repo but was directed to here https://github.com/dan-t/rusty-tags/pull/60#issuecomment-586697650

**Comment by redguardtoo** [comment]
You need bind `C-]` to `counsel-etags-find-tag-at-point` first. 

See http://ergoemacs.org/emacs/keyboard_shortcuts.html

**Comment by ivnsch** [comment]
@redguardtoo Great, it works! I had to use a binding specific for evil mode:
```
(define-key evil-normal-state-map (kbd "C-]") 'counsel-etags-find-tag-at-point)                                                                                                                           
```
