### ISSUE TITLE
enable to make auto-completion works for CSS framworks with company-ctags

### ISSUE THREAD

**Issue by 4goodapp** [redguardtoo/counsel-etags#55]
I created a folder with basics index.html and tailwind.css files in it.
Run the command `ctags -R *` in it.
It generate the file tags with indexed content in it.

I added the following in my emacs init file:
```elisp
(use-package counsel-etags
  :ensure t
  :bind (("C-]" . counsel-etags-find-tag-at-point))
  :init
  (add-hook 'prog-mode-hook
        (lambda ()
          (add-hook 'after-save-hook
            'counsel-etags-virtual-update-tags 'append 'local)))
  :config
  (setq counsel-etags-update-interval 60)
  (push "build" counsel-etags-ignore-directories))

(use-package company-ctags
  ;; :config
  )
(eval-after-load 'company
  '(progn
     (company-ctags-auto-setup)))



(with-eval-after-load 'company-etags '(progn (add-to-list 'company-etags-modes 'web-mode)))
(setq company-etags-everywhere '(html-mode web-mode nxml-mode))

(push '(company-web-html company-etags company-css) company-backends-web-mode)
```

But still, auto-completion doesn't work.

**Comment by redguardtoo** [comment]
Send me the `index.html` and `tailwind.css`, you could place them in gist.

`consel-etags` is for code navigation. It will also help generate and updating tags file. So if you use this package, you don't need run `ctags` in shell.

If you prefer running ctags and generate tags file manually and don't care about code navigation, then you don't need `counsel-etags`.

But your ctags cli is wrong!

 The minimum cli of ctags is "ctags -e -R .", You miss the "-e" option which means "tags file for Emacs"

**Comment by redguardtoo** [comment]
Please also delete lines containing `company-backends-web-mode` and `company-etags`, 

You can run `ctags --list-kind` to see the details of HTML&CSS support.

**Comment by 4goodapp** [comment]
Tailwind CSS: https://unpkg.com/tailwindcss@1.2.0/dist/tailwind.css

The HTML is just a basic template.
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <title>Document</title>
  </head>
  <body>
    <h1 class="bg-blue-300">
      Testing Tailwind
    </h1>
  </body>
</html>
```

**Comment by 4goodapp** [comment]
> The minimum cli of ctags is "ctags -e -R .", You miss the "-e" option which means "tags file for Emacs"

I just run that and it created a different type of tags file.
But still, no auto complete.

**Comment by redguardtoo** [comment]
Maybe you forgot to enable company-mode? See http://company-mode.github.io/ . The minimum setup is only one line.

You can use my emacs.d which just works out of box.https://github.com/redguardtoo/emacs.d

**Comment by 4goodapp** [comment]
Company works for other stuff, but it just doesn't pick complete class name from the CSS files.

> You can use my emacs.d which just works out of box.https://github.com/redguardtoo/emacs.d


this is what I first tried to do actually but as am using my own config along with other like Doom and Spacmacs by using chemacs, this one one assume you don't have multiple config, so switching isn't a smooth process with it.

**Comment by 4goodapp** [comment]
I just install your config, and running `M-x company-complete` does't show any candidates.
Do you have any candidate when you run the command `company-complete`?

**Comment by redguardtoo** [comment]
Thanks. I know what happened.
company-mode will extract prefix from the current editor. Unfortunately company-mode assumes the prefix will contain only alpha-numeric characters. But the universal-ctags extract tag names which could start with special characters like  `:` or `.`.

The easiest workaround is `(setq company-ctags-fuzzy-match-p t)`

![image](https://user-images.githubusercontent.com/184553/77843910-537b5180-71ed-11ea-912c-f03eb002fe1b.png)

There are other solutions, for example, write your own regular expression to override universal ctags' default regular expression.
