### ISSUE TITLE
feature request: exclude directories from common ignored file source

### ISSUE THREAD

**Issue by ztlevi** [redguardtoo/counsel-etags#57]
According to ctags's manual, we could add exclude directories from files, e.g. `--exclude=@.gitignore`

>  --exclude=[pattern]
> If  pattern  begins  with  the character '@', then the rest of the string is interpreted as a file name from
>              which to read exclusion patterns, one per line. If pattern is  empty,  the  list  of  excluded  patterns  is
>               cleared.

Would you mind add such option to `counsel-etags` automatically? Note it requires the file exists, so it's better to handle this inside `counsel-etags` rather the ctags file.

Common ignored file sources are `.gitignore`, `.hgignore`, `.ignore`. While `.ignore` might licated at HOME.

FYI, in your ctags https://gist.github.com/redguardtoo/b12ddae3b8010a276e9b. You could actually define
```
--exclude=*/.hg/*
--exclude=.hg/*
```
as 
```
--exclude=**/.hg/*
```

**Comment by redguardtoo** [comment]
sure. That's doable. Could you double check if both universal ctags and exuberant ctags support this?

**Comment by ztlevi** [comment]
I think it is. 

This is from http://ctags.sourceforge.net/ctags.html.

![image](https://user-images.githubusercontent.com/16655096/81889369-2d6cff00-9558-11ea-92d2-97703a89be13.png)

**Comment by ztlevi** [comment]
I think both of them support it.

http://ctags.sourceforge.net/ctags.html
![image](https://user-images.githubusercontent.com/16655096/81889523-90f72c80-9558-11ea-805d-deae3e08b545.png)

https://docs.ctags.io/en/latest/man/ctags.1.html?highlight=exclude#generate-tag-files-for-source-code
![image](https://user-images.githubusercontent.com/16655096/81889544-9c4a5800-9558-11ea-8bde-7d343ea3c5d3.png)

**Comment by redguardtoo** [comment]
cool. I will do it. maybe this weekend.

**Comment by ztlevi** [comment]
Thanks, appreciate your effort!

**Comment by redguardtoo** [comment]
362fc85 support .gitignore .hgignore ~/.ignore (Chen Bin)

**Comment by redguardtoo** [comment]
As for glob pattern `**/dir/*`, it's not working in `exuberant ctags 5.9`

**Comment by ztlevi** [comment]
OK, is there a 5.9 version? I only see the last stable release is 5.8, and it's 10 years ago. 

Universal ctags is still maintained and overall a better choice. 

But anyway, thanks for your the update!

**Comment by redguardtoo** [comment]
![image](https://user-images.githubusercontent.com/184553/82134149-f177b980-9837-11ea-8e72-9f733ff7a507.png)
