### ISSUE TITLE
TAGS files visited when present in dir

### ISSUE THREAD

**Issue by srustamo** [redguardtoo/counsel-etags#59]
I'm not sure if this is related to this package, but I started noticing that if there is a TAGS file in dir, where I open a file, it gets loaded (visited) automatically. 

Is there a way to prevent auto-visiting of the TAGS file?

**Comment by redguardtoo** [comment]
`counsel-etags` has its own independent cache. It does not share data with `xref` or any other packages. So I'm not sure what "loaded" means. Maybe you are using other ctags/xref packages.

I only use `counsel-etags`. The cache is accessed when user run commands from `consel-etags`. If you set up `after-save-hook` as README instructed. The tags file is updated every 5 minutes.

If you just open a file, nothing happens at `counsel-etags` side.

When you execute a command from `counsel-etag` and cache is empty or outdated, `counsel-etags` tries to find tags file named TAGS in parent directories recursively and use it to fill/update cache.

The file name of tags file could be customized in `counsel-etags-tags-file-name`.

**Comment by srustamo** [comment]
Looks like a local issue in my setup. Thanks.
