### ISSUE TITLE
marker position issues

### ISSUE THREAD

**Issue by RadekRR** [redguardtoo/counsel-etags#6]
Marker position is not saved when fallback function counsel-etags-grep is used.
Second issue: marker is saved even when user decides to quit counsel when selecting candidates (with C-g)

Patch in attachment.
[patch.txt](https://github.com/redguardtoo/counsel-etags/files/1482085/patch.txt)

**Comment by redguardtoo** [comment]
Thanks. Patch is merged.
 ec56d46 fixed markers issue (Chen Bin)
