### ISSUE TITLE
Add Evil's jumplist updating

### ISSUE THREAD

**Issue by srustamo** [redguardtoo/counsel-etags#60]
Is it possible to add a before tag jump hooks to tag finding functions, so that a user add Evil's jumplist update?

Currently jumping to a tag using, say, `counsel-etags-find-tag-at-point`, then <kbd>C-o</kbd> does not jump to the point's earlier location.

**Comment by redguardtoo** [comment]
Great idea. 
502f357 support evil jump list (C-o in evil) (Chen Bin)

**Comment by srustamo** [comment]
Thanks.
