### ISSUE TITLE
提示我etags文件很大70+M，是否打开buffer

### ISSUE THREAD

**Issue by petsgre** [redguardtoo/counsel-etags#62]
提示我etags文件很大70+M，是否打开buffer
然后C-] 就卡住了，很慢

**Comment by redguardtoo** [comment]
第一次载入需要一点时间，之后载入是增量载入，速度很快了。建议看一下README怎么设置。
我试过Linux Kernel 300M TAGS也没有问题。另外etags已不支持。用ctags

**Comment by petsgre** [comment]
确实 但是为什么每次 C-] 都是 No tag find. Grep "xxxx" 呢？
![image](https://user-images.githubusercontent.com/22208613/84611151-8fba7600-aeef-11ea-8ac0-33eb70c4b578.png)

**Comment by redguardtoo** [comment]
看一下TAGS的内容（run  `ctags -e -R .`)。ctags对elisp原生支持还行。但是一些复杂的语法未必支持，要么自己写正则表达式，要么用universtal ctags试试。

**Comment by petsgre** [comment]
ctags -e -R . 
好像是空的 什么都没有
![image](https://user-images.githubusercontent.com/22208613/84628826-ef2e7b00-af1b-11ea-861b-26dca9ebdd90.png)

**Comment by redguardtoo** [comment]
See README for ctags version I support,
```
$ ctags --version
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Aug 19 2018, 23:32:48
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
```

**Comment by petsgre** [comment]
![image](https://user-images.githubusercontent.com/22208613/84631870-b0e78a80-af20-11ea-9655-ba2946400c83.png)
版本也没问题啊

**Comment by redguardtoo** [comment]
TAGS 文件不存在？那你之前那个70M的TAGS文件怎么产生的？

**Comment by petsgre** [comment]
之前存在的，我把TAGS文件删了再测试
执行 counsel-etags-find-tag-at-point
现在就卡住不动了

**Comment by petsgre** [comment]
之前C-]之后 如果没有TAGS文件，他就会create TAGS文件
现在我删了TAGS再 C-]就卡住了

**Comment by redguardtoo** [comment]
把已存在的ctags进程杀掉，或重启电脑

**Comment by petsgre** [comment]
可以创建TAGS了，C-]还是显示no tag found.
而emacs自带的  M-. 可以跳转到当前文件的定义

**Comment by redguardtoo** [comment]
你有没有用一个编辑器打开TAGS，看一下内容？也许是ctags不支持特定的Lisp语法。那么如我所说，只有你自己写regular expression了。

**Comment by petsgre** [comment]
看不懂啊。。。而且都压缩了 2000多行
![image](https://user-images.githubusercontent.com/22208613/84974310-9d713500-b155-11ea-9707-d88e4d6c899a.png)

**Comment by petsgre** [comment]
卡爆了，重启还是卡。。。我的项目是vue的，是不是vue不能用啊
emacs init.el里面就很好

**Comment by redguardtoo** [comment]
If possible, send me the tags file, my mail chenbin.sh@gmail.com

**Comment by petsgre** [comment]
Already sent,please help me to have a look

**Comment by redguardtoo** [comment]
![image](https://user-images.githubusercontent.com/184553/85192986-4069b080-b308-11ea-9cc0-9a267629a5c8.png)

`Vue.config.errorHandler`被作为一个完整的tag name解析出来，如果`counsel-etags-find-tag-at-point`只能用errorHandler搜索的话是找不到的，因为要严格匹配。`counsel-etags-find-tag`是模糊匹配，你可以用它代替。或者你自己写正则表达式把tag name取出来。

性能问题我看你截图基本可以猜到了。Emacs处理长行会非常慢，所以你需要让ctags把包含长行的js文件排除掉，如`*.min.js`或者`*.bundle.js`。建议看一下README。

**Comment by petsgre** [comment]
是有一些min.js文件，怎么可以排除他们呢？
我查看了README中有这个 counsel-etags-imenu-excluded-names 可以吗？

**Comment by redguardtoo** [comment]
建议看我的`~/.ctags`例子，README里有链接的。需要正则表达式的知识。一旦你掌握正则表达式，以及命令行和编辑器结合的知识，就可以大杀四方了，以后用任何编程语言用任何编辑器或IDE都没有问题。

建议你学习我的教程：
51CTO： https://edu.51cto.com/sd/de7e7
163： https://m.study.163.com/provider/480000002228484/index.htm?share=2&shareId=480000002228484

**Comment by petsgre** [comment]
谢大神指导
