### ISSUE TITLE
How to move to the previous position after I run "counsel-etags-find-tag-at-point" ?

### ISSUE THREAD

**Issue by guoqinglei** [redguardtoo/counsel-etags#65]
After run "counsel-etags-find-tag-at-point", the cursor will jump to the place where the  tag is defined. Then what I could do if I want to go back to the previous position ?

I have tried the mark-ring jump, but I don't think it's the best way to do this.

**Comment by redguardtoo** [comment]
`pop-tag-mark`, that's standard command used in Emacs for code navigation.

**Comment by guoqinglei** [comment]
> `pop-tag-mark`, that's standard command used in Emacs for code navigation.

It works. Thanks very much.
