### ISSUE TITLE
counsel-etags-grep cant' follow parameters?

### ISSUE THREAD

**Issue by jason--liu** [redguardtoo/counsel-etags#66]
Hi, thanks for your working of this great tool. And I have a problem here.

System: 
ubuntu 18.04 LTS
emacs26.3

My questions is can counsel-etags-grep  follow parameters?
I have installed ripgrep, cause I know rg do can follow parameters.

like this: 
![image](https://user-images.githubusercontent.com/8001473/87741735-d3b6d880-c817-11ea-9b57-990b035cc14d.png)

It seems that it can not follow parameters.

**Comment by jason--liu** [comment]
Hi, @redguardtoo 
I saw you update the README file. It seems that counsel-etags surpports extra arguments.
Could you explain more specifically about how to Set ?

> Set counsel-etags-grep-extra-arguments to add extra arguments for grep.

Thanks.

**Comment by redguardtoo** [comment]
That's for set grep extra arguments. Not like your problem.

It seems you selected string starts with `-`. 

Fix: ed5c4e1 encode minus sign of selected text before passing it to grep cli (Chen Bin)

**Comment by jason--liu** [comment]
Hi, @redguardtoo 
Thanks for your response. I have updated counsel-etags to latest. 
But it seems that still not surpport arguments when I use counsel-etags-grep.

![image](https://user-images.githubusercontent.com/8001473/88470182-f3db4b80-cf2b-11ea-9b0f-880f2bc391e8.png)

**Comment by redguardtoo** [comment]
Give me a sample file and tell me exact steps.

**Comment by jason--liu** [comment]
Hi, @redguardtoo 
In my situation, it seems there is no need a sample file, cause it can be reproduced in every project.
It looks like counsel-etags error parsing arguments.
Steps:
1. M-x : counsel-etags-grep
2. input what I want, like "-w start_kernel" (searching in Linux kernel project)
3. enter

Then the phenomenon is the same as the picture above.

![Peek 2020-07-26 22-06](https://user-images.githubusercontent.com/8001473/88481146-5ebc6f00-cf8c-11ea-82bd-07695735f37f.gif)

**Comment by redguardtoo** [comment]
In this case, you need input regular expression `\w ....` instead. In Emacs, you can assume the regular expression is always expected in user input.

You can check my tutorial  https://edu.51cto.com/sd/de7e7 which teach everything to master text editor and ide. The regular expression and glob pattern are taught in it too.

Anyway, I changed hint to make it explicit. 7bff2a2 hint for grep (Chen Bin)
