### ISSUE TITLE
emacs asks to reload of TAGS file

### ISSUE THREAD

**Issue by kermorgant** [redguardtoo/counsel-etags#7]
Hello again,

Sorry to bother again, I have a new issue since yesterday : when I save a file (triggering the after-save-hook), emacs asks (and blocks the whole ui) to reload TAGS file saying : Tags file has changed, read new contents ? (y / n)

Note : TAGS file is 30Mb large and also triggers a warning when opening a file withing the project

I have this setup for counsel-etags

```
     (use-package counsel-etags
       :ensure t
       :init
       (setq counsel-etags-update-interval 300) ; 300 seconds, OPTIONAL
       (define-key evil-normal-state-map (kbd "M-g") 'counsel-etags-find-tag-at-point)
       (add-hook 'prog-mode-hook
                 (lambda ()
                   (add-hook 'after-save-hook
                             'counsel-etags-virtual-update-tags 'append 'local)))
       )
```

![gscreenshot_2017-11-21-094649](https://user-images.githubusercontent.com/10561580/33094197-02e01bd2-cf08-11e7-83e4-9e5ede81ce4e.png)

Besides, it opens a window with ctags warnings. 

My setup : emacs 25.3 / archlinux

Would you have any idea of what is going on ?
Regards

**Comment by redguardtoo** [comment]
You can set up variables `grep-find-ignored-files` and `grep-find-ignored-directories`:
```lisp
(eval-after-load 'grep
  '(progn
     (dolist (v '("auto"
                  "target"
                  "node_modules"
                  "bower_components"
                  "*dist"
                  ".sass_cache"
                  ".cache"
                  ".npm"
                  "elpa"))
       (add-to-list 'grep-find-ignored-directories v))

     (dolist (v '("*.min.js"
                  "*.map"
                  "*.bundle.js"
                  "*.min.css"
                  "tags"
                  "TAGS"
                  "GTAGS"
                  "GRTAGS"
                  "GPATH"
                  "cscope.files"
                  "*.json"
                  "*.log"))
       (add-to-list 'grep-find-ignored-files v))))
```

To eliminate warnings,
```lisp
;; Don't ask before rereading the TAGS files if they have changed
(setq tags-revert-without-query t)
;; Don't warn when TAGS files are large
(setq large-file-warning-threshold nil)
```

You may want to check my Emacs setup at https://github.com/redguardtoo/emacs.d/blob/master/lisp/init-ctags.el

**Comment by kermorgant** [comment]
Thanks again @redguardtoo !
