### ISSUE TITLE
How to color candidate/selection when 'counsel-etags-grep' like swiper does?

### ISSUE THREAD

**Issue by zwpdbh** [redguardtoo/counsel-etags#71]
Thanks for providing such a powerful tool which is powerful and easy to use. 
When I run 'counsel-etags-grep', how do I customize the selection/candidate in the file like swiper does?
 
When using swiper, the highlight is shown in the corresponding file:
![highlight-selection-candidate](https://user-images.githubusercontent.com/4442806/92985575-7de47100-f4e6-11ea-8c65-731fd5cc1a87.png)

When using counsel-etags-grep, the corresponding file has no highlight for selection.
![no-highlight-how-to-customize](https://user-images.githubusercontent.com/4442806/92985579-8472e880-f4e6-11ea-994a-e740ceb4172a.png)

**Comment by redguardtoo** [comment]
swiper and counsel-etags-grep uses same api `ivy-read`. ivy will highlight the string users have input.

Please note in `counsel-etags-grep`, user input is empty because I filter the candidates before feeding them into ivy-read.

My solution's benefit is you can immediately filter the displayed candidates without moving focus.

For example, in swiper if you search "keyword1", the `keyword1` is displayed in ivy ui. So it's impossible to filter the candidates further with "keyword2" if "keyword2" could either be before or after the "keyword1" in one line.

**Comment by zwpdbh** [comment]
Thanks for your help.

Now, I see the differences: it is not even highlighted in minibuffer. 

> My solution's benefit is you can immediately filter the displayed candidates without moving focus.
But sometimes, user really need to visit each candidate in the file quickly to show their up and down context. So, they could know whether a candidate is really what they need.

So, I created a extend function:
```
(defun zw/counsel-etags-grep-at-point ()
  (interactive)
  (counsel-etags-grep (counsel-etags-tagname-at-point) nil nil))
```
which is used as finding references.
Then, I changed keybinding for ivy
```
  (define-key ivy-minibuffer-map (kbd "C-n") 'ivy-next-line-and-call)
  (define-key ivy-minibuffer-map (kbd "C-p") 'ivy-previous-line-and-call)
```
Now, I could move quickly in minibuffer and see the corresponding part in big window, without loosing focus in minibuffer.

Based on this, would you like to give suggestions on how to highlight the part both in minibuffer and in corresponding visisting file ?

**Comment by redguardtoo** [comment]
1cab357 could display keyword in grep ui (Chen Bin)

**Comment by zwpdbh** [comment]
Thanks for the modification. It could show the highlight in minibuffer for keywords now.  💯 

But the keywords in the corresponding visited file is still not highlighted. 
I have tried to customize-group  ivy-faces.  But the faces in it has no effect. 

Is there a way to do the highlight in the visited file buffer, as well ?   

Thanks a lot for your modification.

**Comment by redguardtoo** [comment]
ec224dc 2020-09-11 can show tag name in minibuffer (Chen Bin)

**Comment by zwpdbh** [comment]
Thanks a lot for the changes.  But the code is not highlighted, see screenshot below.

![highlight](https://user-images.githubusercontent.com/4442806/92985102-217f5280-f4e2-11ea-80c4-1fd643662aec.gif)

The gif shows the differences between ~helm-projectile-ag~ and ~(counsel-etags-grep (counsel-etags-tagname-at-point) nil nil t)~. 
When the selection from minibuffer switches, to visit the actual position in the code. The tag should be highlighted in the code buffer. ~helm-projectile-ag~ could do this. 
But currently, counsel-etags-grep is not highlighted for the code (it could only highlight the part in minibuffer).

While I am reading your changes and ivy's code,  could you give more detailed suggestion on how to use your changes to achieve this?

**Comment by redguardtoo** [comment]
Default UI of `counsel-etags-grep` or `counsel-etags-find-tag-at-point` is not changed. I added some extra parameters to those command so you can create your own command based on them.

**Comment by zwpdbh** [comment]
Thansk a lot. I will give it a try.
