### ISSUE TITLE
how to do case insensitive grep?

### ISSUE THREAD

**Issue by endlessMagic** [redguardtoo/counsel-etags#73]
I cannot find a way to do case insensitive grep in the README.org and simply add -i won't work as it will be seen as part of the search pattern.

**Comment by redguardtoo** [comment]
You mean the command `counsel-etags-grep`? Or the tag search command?

**Comment by endlessMagic** [comment]
I am using the counsel-etags-grep command.

**Comment by redguardtoo** [comment]
See `counsel-etags-grep-extra-arguments`

**Comment by endlessMagic** [comment]
Thank you very much!
