### ISSUE TITLE
Ctags Will Scan Code When Jump Next Tag

### ISSUE THREAD

**Issue by maobaoqi** [redguardtoo/counsel-etags#76]
Hi,
I create tags for /usr/include and /usr/local/include directory files and the TAGS file is under my a home directory which called tags.
Set counsel-etags-extra-tags-files to point the /home/myname/tags/TAGS path.
And now, create new c file in a project directory, in this c file, can jump to a tag for example sqlite3 struct but in the sqlite3 struct .h file, can not
jump function to another tag place. It appear "ctags will scan code at /usr/include/" in minibuffer.

**Comment by maobaoqi** [comment]
Test on windows10 msys2, jump works well and can get into next tag and next tag. Prompt "ctags will scan code at /usr/include" appears on Linux.

**Comment by maobaoqi** [comment]
I look up counsel-etags source code and comment like this, it can solve current problem temporarily but use .dir-locals.el also can not work.
![2021-02-24 16-01-33屏幕截图](https://user-images.githubusercontent.com/3353791/108967071-fd8f8200-76b9-11eb-95ce-a80b3ef8615d.png)

**Comment by redguardtoo** [comment]
I see. Let me have a look.

**Comment by redguardtoo** [comment]
9164ba3 can navigate inside third party project with no tags file in its root (Chen Bin)

**Comment by maobaoqi** [comment]
@redguardtoo using the new counsel-etags.el to replace old and the problem also appear (test on linux system)

**Comment by redguardtoo** [comment]
create a toy project,

content  of ` prj1/hello.js`,
```javascript
function hello() {
}
hello();
lib1();
lib2();
```

content of `prj2/lib.js`,
```javascript
function lib1() {
}

function lib2() {
}
lib1();
lib2();
```

Create directory `thirdparty`.

In `prj1`, create its TAGS by `ctags -e -R .`

Create TAGS of `prj2` and move it to `thirdparty` by `cd prj2 && find $PWD -name "*.js" | ctags -e -L - && mv TAGS ../thirdparty`

In you Emacs, add full path of `thirdparty/TAGS` into `counsel-etags-extra-tags-files`.

Now reproduce the bug in this toy project and give me the details.

**Comment by maobaoqi** [comment]
@redguardtoo step by step to create prj1 and prj2 tags and can not jump. the debug information is below. 
![Screenshot from 2021-02-25 22-19-10](https://user-images.githubusercontent.com/3353791/109166616-db7c2980-77b7-11eb-93cd-ac753e8aa6ca.png)
![Screenshot from 2021-02-25 22-24-20](https://user-images.githubusercontent.com/3353791/109166987-3f9eed80-77b8-11eb-9822-e8394c1819c8.png)

**Comment by maobaoqi** [comment]
generate tags for /usr/local/include/* and put tags into /home/username/tags2dev then set counsel-etags-extra-tags-files, in a c file the next second jump can not work and pop up like this. Could you repeat this problem?
![Screenshot from 2021-02-25 22-27-57](https://user-images.githubusercontent.com/3353791/109167853-2c405200-77b9-11eb-8fe2-db65cfda1b4c.png)
![Screenshot from 2021-02-25 22-34-27](https://user-images.githubusercontent.com/3353791/109168326-a8d33080-77b9-11eb-9521-6b6e52acd528.png)

**Comment by redguardtoo** [comment]
The error output in toy project does not make sense. You are calling `js-find-symbol`. should use `counsel-etags-find-tag-at-point`.

**Comment by maobaoqi** [comment]
@redguardtoo in c file, when set counsel-etags-extra-tags-files global and the new package works well. when set counsel-etags-extra-tags-files in project .dir-locals.el as local variable. multi jump in extra header files can not work.

**Comment by redguardtoo** [comment]
Yes. `.dir-locals.el` only set variables in one directory. You can make `counsel-etags-extra-tags-files` global or set it in `prog-mode-hook`.

**Comment by maobaoqi** [comment]
ok. I am looking for how to set variables in project .dir-locals.el file for extern another directory. mybe this method can slove finally.
thanks for your reply. and now jump through many libraries works very fluently.

This issue can be closed. thanks!

**Comment by redguardtoo** [comment]
x
