### ISSUE TITLE
How to go back to previous position after I executed counsel-etags-find-tag-at-point ?

### ISSUE THREAD

**Issue by guoqinglei** [redguardtoo/counsel-etags#77]
If I executed counsel-etags-find-tag-at-point and jumped somewhere, how could I come back to the previous position before  I had executed counsel-etags-find-tag-at-point ?

**Comment by redguardtoo** [comment]
`M-x pop-tag-mark`. That's common practice. Used in almost every plugin.

**Comment by guoqinglei** [comment]
Thanks a lot. It works well.
