### ISSUE TITLE
about ctags cache

### ISSUE THREAD

**Issue by tt67wq** [redguardtoo/counsel-etags#82]
When I dropped some code or moved some code block from one file to another, I rescaned my project, but etags navigated me to a wrong place, and that is caused by tags cache.
```
(when (and tags-file (file-exists-p tags-file)
               ;; TAGS file is smaller when being created.
               ;; Do NOT load incomplete tags file
               (< (counsel-etags-cache-filesize tags-file)
                  (setq file-size (nth 7 (file-attributes tags-file)))))
      (when counsel-etags-debug
        (message "Read file .... %s %s" (counsel-etags-cache-filesize tags-file) file-size))
      (counsel-etags-put (intern tags-file)
                         (list :content
                               (counsel-etags-read-file tags-file)
                               :filesize
                               file-size)
                         counsel-etags-cache))
```

I was wondering if we can replace '<' to '\/='?

**Comment by redguardtoo** [comment]
You could set `counsel-etags-update-interval` to a smaller value. Or `M-x counsel-etags-update-tags-force`.

**Comment by tt67wq** [comment]
thank u. `counsel-etags-update-tags-force` regenerates tag file, but cache still exists and leads to wrong line, will `counsel-etags-update-tags-force` evict cache?

**Comment by redguardtoo** [comment]
eb6a131 invalidate cache when force updating tags file (Chen Bin)

**Comment by tt67wq** [comment]
respect!
