### ISSUE TITLE
How can I append external tags?

### ISSUE THREAD

**Issue by VernonGrant** [redguardtoo/counsel-etags#84]
Hi,

Thanks for this awesome extension! I'm wondering how should I go about appending the tags of external dependencies on a per-project basis. Usually I would do this by running ctags within the project root, and appending the dependency's tags to my projects tags file, something like this:

```shell
# I would cd into my project root and generate the tags for the project's source:
ctags -f TAGS -e -R ./

# I would then append the dependency's tags to my projects tags file.
# Notice the -a, --append argument.
ctags -f TAGS -e -a -R /usr/include/freetype/
``` 

How can I do the same using `counsel-etags`? 

Thanks!

**Comment by redguardtoo** [comment]
See https://github.com/redguardtoo/counsel-etags#specify-multiple-tags-files

**Comment by redguardtoo** [comment]
Or you can replace this program's default backend with your own backend where you can run whatever ctags command you like,

See https://github.com/redguardtoo/counsel-etags#auto-update-tags-file

**Comment by VernonGrant** [comment]
Ok, thanks! I just wanted to make sure there wasn't something obvious I missed.

**Comment by redguardtoo** [comment]
You can also use hook, https://github.com/redguardtoo/counsel-etags#insert-extra-content-into-tags-file-after-its-updated

I designed the hook to use Emacs Lisp to append extra content into existing tags. But you can also run some shell command line in the hook.
