### ISSUE TITLE
Please don't provide a feature in my-byte-compile

### ISSUE THREAD

**Issue by tarsius** [redguardtoo/counsel-etags#85]
You have recently added a test utility `my-byte-compile.el` to many of your packages (at least counsel-etags, eacl, elpa-mirror, evil-matchit, evil-nerd-commenter, find-file-in-project, mybigword, shellcop, shenshou, vc-msg and wucuo.

This file provides the matching feature using `provide`, which means that tools that determine the libraries in a repository by looking for elisp files that provide a feature, will wrongly conclude that this is library. Only libraries should provide a feature; utility files should not provide a feature and should be loaded by path. And because most (all?) of your packages provide that feature emir, the tools used to maintain the Emacsmirror, concludes that these packages conflict with one another.

You load this file by path already: `emacs ... -l test/my-byte-compile.el`, so you can just drop the `provide`. Thanks for considering this change.

By the way, the headers and footers of these files say "my-elint.el".

**Comment by redguardtoo** [comment]
Thanks for the heads up. All my project have been updated per your suggestion.

**Comment by tarsius** [comment]
Thanks a lot!
