### ISSUE TITLE
"No tag is found." although TAGS file contains this tag

### ISSUE THREAD

**Issue by schoettl** [redguardtoo/counsel-etags#86]
Hi,

Thanks for this package! It works really nice but sometimes it fails to find a tag and falls back to ripgrep.

I don't understand why it doesn't find the tag:

- I have exactly one `TAGS` file in my (git) project root directory.
- In my Haskell files, `counsel-etags-find-tag-at-point` works.
- In a .julius (JavaScript) file it says "No tag is found." but the function name definitely exists in `TAGS`.

The mode where it fails is `shakespeare-julius-mode` which is directly derived from `javascript-mode`. But it also fails when I switch to `javascript-mode`.

I don't understand why... the line the TAGS file look normal:

```
function saveSitesToLocalStorageIfChanged() {saveSitesToLocalStorageIfChanged131,4226
```

Any ideas?

**Comment by redguardtoo** [comment]
Ctags version? I also need a minimum example to reproduce the issue. 

You also need `(setq counsel-etags-debug t)` and reproduce the issue. Then send me the full output in *Messages* buffer.

**Comment by schoettl** [comment]
Today, it's not reproducible anymore – I have no idea why.

The TAGS file looks the same, only the line numbers have changed after a update. 

Thank you! In case it re-occurs, I'll provide more information.

**Comment by schoettl** [comment]
I have this problem again from time to time in different Haskell projects.
After a restart of emacs it worked again. I just leave a comment to track this down next time...

```
$ rg --files -g\!static/ | ctags -e -L- --languages=Haskell
$  ls -l TAGS
-rw-r--r-- 1 jakob users 29679 Mar  1 11:08 TAGS
$ grep getRequisits TAGS
getRequisits = dogetRequisits64,2241
getRequisits = dogetRequisits66,2808

```

`(counsel-etags-tags-file-directory)` is correct with `/home/usr/projects/project`.

After `M-x counsel-etags-find-tag-at-point`, the message buffer is:

```
counsel-etags-find-tag-api called => tagname=getRequisits fuzzy=nil dir/home/usr/projects/project/ current-file=/home/usr/projects/project/src/Handler/SupplyCheck.hs
counsel-etags-extract-cands called. tags-file=/home/usr/projects/project/TAGS cached-file-size=3259796 tags-file-size=34761
counsel-etags-extract-cands called. tags-file=/home/usr/projects/project/TAGS tagname=getRequisits
counsel-etags-collect-cands called. tags-file=/home/usr/projects/project/TAGS cands=nil
counsel-etags-grep called: keyword=getRequisits
  root=/home/usr/projects/project/
  cmd="/run/current-system/sw/bin/rg" -n -M 1024 --no-heading --color never -s   --hidden -g="!.git/*" -g="!.svn/*" -g="!.cvs/*" -g="!.bzr/*" -g="!.hg/*" -g="!bin/*" -g="!dist/*" -g="!fonts/*" -g="!images/*" -g="!.DS_Store/*" -g="!.npm/*" -g="!.tmp/*" -g="!.sass-cache/*" -g="!.idea/*" -g="!node_modules/*" -g="!bower_components/*" -g="!.tox/*" -g="!.vscode/*" -g="!.cask/*" -g="!\*.log" -g="!rusty-tags.vim" -g="!rusty-tags.emacs" -g="!tags" -g="!TAGS" -g="!\*.tgz" -g="!\*.gz" -g="!\*.xz" -g="!\*.zip" -g="!\*.tar" -g="!\*.rar" -g="!GTAGS" -g="!GPATH" -g="!GRTAGS" -g="!cscope.files" -g="!\*bundle.js" -g="!\*min.js" -g="!\*min.css" -g="!\*.png" -g="!\*.jpg" -g="!\*.jpeg" -g="!\*.gif" -g="!\*.bmp" -g="!\*.tiff" -g="!\*.ico" -g="!\*.doc" -g="!\*.docx" -g="!\*.xls" -g="!\*.ppt" -g="!\*.pdf" -g="!\*.odt" -g="!.clang-format" -g="!\*.obj" -g="!\*.so" -g="!\*.o" -g="!\*.a" -g="!\*.ifso" -g="!\*.tbd" -g="!\*.dylib" -g="!\*.lib" -g="!\*.d" -g="!\*.dll" -g="!\*.exe" -g="!.metadata\*" -g="!\*.class" -g="!\*.war" -g="!\*.jar" -g="!\*flymake" -g="!\#\*\#" -g="!.\#\*" -g="!\*.swp" -g="!\*\~" -g="!\*.elc" -g="!\*.pyc" "getRequisits" --
  cands=(src/Handler/SupplyCheck.hs:46:  (now, tz, searchterm, searchterm', articles, app, settings, baseUrl) <- getRequisits src/Handler/SupplyCheck.hs:63:-- getRequisits :: Handler (UTCTime, TimeZone, String, String, a, App, AppSettings, String) src/Handler/SupplyCheck.hs:64:getRequisits = do src/Handler/SupplyOrder.hs:32:  (now, tz, searchterm, articleId, articleNumber, articleName, supplierId, app, settings, baseUrl) <- getRequisits src/Handler/SupplyOrder.hs:43:  (now, tz, searchterm, articleId, articleNumber, articleName, supplierId, app, settings, baseUrl) <- getRequisits src/Handler/SupplyOrder.hs:66:getRequisits = do)
Quit
```

**Comment by redguardtoo** [comment]
See `counsel-etags-update-interval`

**Comment by schoettl** [comment]
Thanks for this hint. I somehow forgot that counsel-etags generates the TAGS file automatically.

I think this issue was a combination of

- exurbant ctags (which doesn't support Haskell),
- counsel-etags which overwrites my TAGS file (I wasn't aware of this first)
- somehow TAGS files were created in subdirectories and only contained tags of that directory
- maybe tag jumping across different languages is not fully supported or not always possible

Still testing to find the best setup for me…

**Comment by redguardtoo** [comment]
You can use `universal-tags` to generate tags file. Select a directory you are working on as your project root and let `counsel-etags` or any tool you prefer to generate tags. Use `counsel-etags-extra-tags-files` to import extra tags files.
