### ISSUE TITLE
Find command produces unexpected results

### ISSUE THREAD

**Issue by nilsdeppe** [redguardtoo/counsel-etags#9]
First off, thanks for the awesome package and the hard work you've put in!

I noticed that the find command does not do what I expect it to for what appears to be two separate reasons.

1. File names are not correctly ignored because the find command is executed as `find . ... -not -name "\*.json"` when it should be `find . ... -not -name "*.json"`. This is resolved by removing the `(shell-quote-argument n)` call [here](https://github.com/redguardtoo/counsel-etags/blob/3392436e99b2477687aabd2f54d32a2acaa94606/counsel-etags.el#L344) and replacing it with `n`. This boils down to not needing to shell-quote arguments that are passed to the shell as literal quotes.

2. If I try to ignore the directories `build*`, e.g. `build_clang`, `build_gcc`, etc. by using `(add-to-list 'counsel-etags-ignore-directories '"build*")` the find command fails. Find is executed as `find . \( ... -iwholename "*build\*/*" ...\)` which does not work. The desired call is `find . \(... -iwholename "*build*" ...\)`. This requires changing the line [here](https://github.com/redguardtoo/counsel-etags/blob/3392436e99b2477687aabd2f54d32a2acaa94606/counsel-etags.el#L340) from `(shell-quote-argument (file-name-as-directory p))` to `p`.

These two issues may be related to find behaving differently on UNIX and Linux, but I'm not sure.

OS: `Arch Linux`
Emacs: `25.3.1`
Project uses: `git`
CTags: 
```
Universal Ctags 0.0.0(04a8f1f6), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec 27 2017, 00:24:29
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +multibyte, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml
```
find:
```
find (GNU findutils) 4.6.0
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Eric B. Decker, James Youngman, and Kevin Dalley.
Features enabled: D_TYPE O_NOFOLLOW(enabled) LEAF_OPTIMISATION FTS(FTS_CWDFD) CBO(level=2) 
```
counsel-etags: `20171215.2123`

Note: This may be useful for #5

**Comment by redguardtoo** [comment]
Thanks. See 921fa5a fixed issues on ignore patterns (Chen Bin)

`counsel-etags-ignore-directories` does not support wildcast. This flag is used by  `find`, `ripgrep`, and `grep`. It's difficult to convert it to option compatible with all these programs.

But `counsel-etags-ignore-filenames` supports wildcast now. 

I removed `shell-quote-argument` from my code.

**Comment by nilsdeppe** [comment]
Awesome, thanks for the quick fix. I'll give it a try later on. One thing I noticed in the diff is a `(message ...)` call [here](https://github.com/redguardtoo/counsel-etags/blob/921fa5a062bda9a0f9226fdaa76530ad809ff7b9/counsel-etags.el#L312) that looks to be something used during debugging that the user likely doesn't care about.

**Comment by redguardtoo** [comment]
Fixed. Thanks

**Comment by nilsdeppe** [comment]
Great, thank you!
